### ISSUE TITLE
OS X make failed.

### ISSUE THREAD

**Issue by ghost** [samhare/struck#1]
zp@ZPdeMacBook-Pro  ~/Desktop/opencv worksapce/struck-1-master/build   master  make
[  7%] Building CXX object CMakeFiles/struck.dir/src/ImageRep.cpp.o
/Users/zp/Desktop/opencv worksapce/struck-1-master/src/ImageRep.cpp:66:4: error:
      use of undeclared identifier 'cvtColor'; did you mean 'cvCvtColor'?
                        cvtColor(image, m_images[0], CV_RGB2GRAY);
                        ^~~~~~~~
                        cvCvtColor
/usr/local/include/opencv2/imgproc/imgproc_c.h:203:14: note: 'cvCvtColor'
      declared here
CVAPI(void)  cvCvtColor( const CvArr\* src, CvArr\* dst, int code );
             ^
/Users/zp/Desktop/opencv worksapce/struck-1-master/src/ImageRep.cpp:66:13: error:
      no viable conversion from 'const cv::Mat' to 'const CvArr _'
      (aka 'const void *')
                        cvtColor(image, m_images[0], CV_RGB2GRAY);
                                 ^~~~~
/usr/local/include/opencv2/core/mat.hpp:1489:28: note: candidate template
      ignored: could not match 'vector<type-parameter-0-0,
      allocator<type-parameter-0-0> >' against 'const void *'
    template<typename _Tp> operator std::vector<_Tp>() const;
                           ^
/usr/local/include/opencv2/core/mat.hpp:1490:35: note: candidate template
      ignored: could not match 'Vec<type-parameter-0-0, cn>' against
      'const void *'
    template<typename _Tp, int n> operator Vec<_Tp, n>() const;
                                  ^
/usr/local/include/opencv2/core/mat.hpp:1491:42: note: candidate template
      ignored: could not match 'Matx<type-parameter-0-0, m, n>' against
      'const void *'
    template<typename _Tp, int m, int n> operator Matx<_Tp, m, n>() const;
                                         ^
/usr/local/include/opencv2/imgproc/imgproc_c.h:203:39: note: passing argument to
      parameter 'src' here
CVAPI(void)  cvCvtColor( const CvArr_ src, CvArr\* dst, int code );
                                      ^
/Users/zp/Desktop/opencv worksapce/struck-1-master/src/ImageRep.cpp:79:4: error:
      use of undeclared identifier 'integral'
                        integral(m_images[i], m_integralImages[i]);
                        ^
/Users/zp/Desktop/opencv worksapce/struck-1-master/src/ImageRep.cpp:102:4: error:
      use of undeclared identifier 'integral'
                        integral(tmp, m_integralHistImages[j]);
                        ^
4 errors generated.
make[2]: **\* [CMakeFiles/struck.dir/src/ImageRep.cpp.o] Error 1
make[1]: **\* [CMakeFiles/struck.dir/all] Error 2
make: **\* [all] Error 2

**Comment by hedes1992** [comment]
I replace all the opencv_include to "#include <opencv2/opencv.hpp>", because I install opencv2 on my ubuntu 14.04.
So maybe you can check your opencv version?
