### ISSUE TITLE
The sequences data url can't access

### ISSUE THREAD

**Issue by lzjqsdd** [samhare/struck#2]
http://vision.ucsd.edu/~bbabenko/project_miltrack.html
this address seems not work.My  browser get:Gateway Timeout

**Comment by C-peng** [comment]
yes, I also need,do you deal with

**Comment by lzjqsdd** [comment]
I hava download a benchmark dataset which includes the girl dataset [https://sites.google.com/site/trackerbenchmark/benchmarks/v10](url)

you can also use this code with dataset, [https://github.com/lzjqsdd/MLCode/tree/master/cv/Tracking/struck/origin](url),I'v revised some code ,and the project can run well.

**Comment by C-peng** [comment]
thanks,I will have a try.
